// Data converted from JSON files for database seeding

export const employeeSeedData = [
  { name: "Zoë Robins", department: "Administration" },
  { name: "Madeleine Madden", department: "Administration" },
  { name: "Josha Sadowski", department: "Audit" },
  { name: "Kate Fleetwood", department: "Audit" },
  { name: "Priyanka Bose", department: "Banking Operations" },
  { name: "Hammed Animashaun", department: "Banking Operations" },
  { name: "Álvaro Morte", department: "Banking Operations" },
  { name: "Taylor Napier", department: "Banking Operations" },
  { name: "Alan Simmonds", department: "Banking Operations" },
  { name: "Gil Cardinal", department: "Communications" },
  { name: "Richard J. Lewis", department: "Communications" },
  { name: "Randy Bradshaw", department: "Corporate Services" },
  { name: "Tracey Cook", department: "Corporate Services" },
  { name: "Lubomir Mykytiuk", department: "Corporate Services" },
  { name: "Dakota House", department: "Facilities" },
  { name: "Lori Lea Okemah", department: "Facilities" },
  { name: "Renae Morrisseau", department: "Facilities" },
  { name: "Rick Belcourt", department: "Facilities" },
  { name: "Selina Hanusa", department: "Financial Services" },
  { name: "Buffy Gaudry", department: "Financial Services" },
  { name: "Shaneen Ann Fox", department: "Financial Services" },
  { name: "Allan Little", department: "Financial Services" },
  { name: "Danny Rabbit", department: "Financial Services" },
  { name: "Jesse Ed Azure", department: "Human Resources" },
  { name: "Stacy Da Silva", department: "Human Resources" },
  { name: "Vladimír Valenta", department: "Human Resources" },
  { name: "Samone Sayeses-Whitney", department: "Human Resources" },
  { name: "Paul Coeur", department: "Human Resources" },
  { name: "Graham Greene", department: "Information Technology" },
  { name: "Sandika Evergreen", department: "Information Technology" },
  { name: "Jennifer Rodriguez (Software Developer)", department: "Information Technology" },
  { name: "Aiyana Littlebear", department: "IT Technician" },
  { name: "Inara Thunderbird", department: "IT Technician" },
  { name: "Kaya Runningbrook", department: "IT Technician" },
  { name: "Elara Firehawk", department: "IT Technician" },
  { name: "Siona Moonflower", department: "IT Technician" },
  { name: "Kaiyu Greywolf", department: "IT Technician" },
  { name: "Ayawamat Nightwind", department: "IT Technician" },
  { name: "Tala Braveheart", department: "IT Technician" },
  { name: "Iniko Stonebear", department: "IT Technician" },
  { name: "Onatah Redhawk", department: "IT Technician" },
];

export const roleSeedData = [
  { name: "Jo-Anne Sinclair (CEO/Chair of Board)", department: "Executive Leadership" },
  { name: "Jackson Smith (COO/VP Operations)", department: "Executive Leadership" },
  { name: "Susan Thomas (CFO/VP Administration)", department: "Executive Leadership" },
  { name: "Richa Kaur (VP Client Services)", department: "Executive Leadership" },
  { name: "Josee Benjamin (CIO)", department: "Executive Leadership" },
  { name: "Vincent Grey (VP Sales & Marketing)", department: "Executive Leadership" },
  { name: "Rupa Kharki (Director Financial and Audit Svcs)", department: "Directors" },
  { name: "Xun Kuang (Director Human Resources)", department: "Directors" },
  { name: "Stien Pedersen (Director Legal Services/General Counsel)", department: "Directors" },
  { name: "Sandra Bear (Director Information Technology)", department: "Directors" },
  { name: "Gus Blue (Director Information Security and CISSO)", department: "Directors" },
  { name: "Sam Kong (Director Accounting)", department: "Directors" },
  { name: "Valentine Smith (Director Physical Security)", department: "Directors" },
  { name: "Mariya Kaperski (Director Facilities)", department: "Directors" },
  { name: "Abd al-Hamid Alami (Manager, Business Continuity and Disaster Recovery)", department: "Management" },
  { name: "Victoria Gray (Manager, Internal Audit)", department: "Management" },
  { name: "Cheryl Guru (Chief Architect)", department: "Management" },
  { name: "Jean Ngoy (Manager, Security Architecture)", department: "Management" },
  { name: "Kris Gold (Solution Architect, Online Banking)", department: "Management" },
  { name: "Isaac Smith (Manager, Application Solutions)", department: "Management" },
  { name: "Payton Frost (Lead Developer, Online Banking)", department: "Management" },
  { name: "Samantha Nettle (Manager, Operational Risk)", department: "Management" },
  { name: "Yolanda Ferreira (Manager, Vendor Relations)", department: "Management" },
  { name: "Samir Hassan (Manager, Purchasing)", department: "Management" },
  { name: "Yuna Aikawa (Manager, Communications)", department: "Management" },
  { name: "Jonathan Carberry (Manager Customer Experience and Community Eng.)", department: "Management" },
  { name: "Roland Wei (Manager of Sales)", department: "Management" },
  { name: "Pran Singh (Manager, Marketing)", department: "Management" },
  { name: "Linda Analyst (Business Analyst, Online Banking)", department: "Management" },
  { name: "Esra Sedge (Manager, Contract Management)", department: "Management" },
  { name: "Pranee Tan (Manager, Compliance Management)", department: "Management" },
  { name: "Karmen Spruce (Manager IT End User Service Desk)", department: "IT Management" },
  { name: "Haydar Katirci (Manager IT End User Computing)", department: "IT Management" },
  { name: "Jill Harkness (Manager IT Telecom and Infrastructure)", department: "IT Management" },
  { name: "Tim Morrison (Manager, Data Center and Hosting Services)", department: "IT Management" },
  { name: "Aleksandr Milosevic (Manager of IT Risk Management)", department: "IT Management" },
  { name: "Jim Wingnut (Manager IT, Project Management Office)", department: "IT Management" },
  { name: "Left Vacant for future expansion", department: "Vacant Roles" },
  { name: "Left Vacant for future expansion", department: "Vacant Roles" },
  { name: "Left Vacant for future expansion", department: "Vacant Roles" },
  { name: "Left Vacant for future expansion", department: "Vacant Roles" },
  { name: "Left Vacant for future expansion", department: "Vacant Roles" },
];
